dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 256 # for vit s adapt to MAX GPU can handle
  dataset_path: CustomImageDataset:split=TRAIN:root=/fileroot
  centering: sinkhorn_knopp # adapt
student:
  arch: vit_small
  patch_size: 14
  drop_path_rate: 0.4
  drop_path_uniform: false
  ffn_layer: mlp #"swiglufused" or "mlp"
  block_chunks: 4
  in_chans: 4
teacher:
  momentum_teacher: 0.994
  in_chans: 4
optim:
  epochs: 100 # prolly high enough right
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  global_crops_size: 224  #original 224 -> 518 necessary for loading checkpoints, however, interpolation can be used to adapt the size
  local_crops_size: 98 # div/14 round number
